version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: demo_db

# to run all service , do this in terminal docker-compose up -d, but to run just one , do docker-compose up db -d, where db is the name of the exact one u want to run
# this allows u to run it on docker in ur system
# npm i @nestjs/typeorm typeorm pg  provides support (object relational pavkage )
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@demo.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - db

#  Accessing pgAdmin in your browser:
# URL: http://localhost:5050

# Email: admin@demo.com

# Password: admin123

# Then:

# Click "Add New Server"

# Use these connection details:

# Name: anything (e.g., Local DB)

# Host: db

# Port: 5432

# Username: postgres

# Password: pass123

# Database: demo_db

# ✅ Done! You now have a Postgres UI.

